NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

CoreApiBundle:
    resource: "@CoreCoreBundle/Resources/config/routing.yml"
    prefix:   /api
