parameters:
#    core_core.example.class: Core\CoreBundle\Example

services:
#    core_core.example:
#        class: %core_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
